### ISSUE TITLE
How could I retrieve the pull request details

### ISSUE THREAD

**Issue by xbax486** [lokalise/python-lokalise-api#113]
**The feature I'd like is to retrieve the pull request details of a feature branch** 

**Additional context**
Hi mate. Is there any support for getting the pull requests details in the documentation? I could not find any of it. It would be better if I could get the pull request URL. Thank you.

**Comment by bodrovis** [comment]
If we are talking about Lokalise GitHub integration and the corresponding pull request URL, I don't think there's a way to retreive it, unfortunately as the API does not provide such functionality. Using the API, you can trigger GH integration (by using the Download files endpoint) but that's pretty much it. If you require this feature, I would really recommend reaching out the the customer support at lokalise.com (there's a chat widget at the bottom) so that they can gather some info and forward this request to the proper team.

**Comment by xbax486** [comment]
> If we are talking about Lokalise GitHub integration and the corresponding pull request URL, I don't think there's a way to retreive it, unfortunately as the API does not provide such functionality. Using the API, you can trigger GH integration (by using the Download files endpoint) but that's pretty much it. If you require this feature, I would really recommend reaching out the the customer support at lokalise.com (there's a chat widget at the bottom) so that they can gather some info and forward this request to the proper team.

Hi Bodrovis, thank you for your reply. Actually, the integration is Bitbucket related. Right now, I am able to get Lokalise to create a pull request automatically based on specific event, like key changes. However, there is no information regarding the pull request returned from Lokalise. Just want to get the newly created pull request URL if it is created by Lokalise. Will ask the Lokalise customer support regarding this. Again, thank you.

**Comment by bodrovis** [comment]
No problems! Yeah, I'm afraid we don't provide such info via the API but perhaps the CS guys can provide some more info. :)
